[package]
name = "utilities"
version = "1.0.0"
description = "Simple, helpful class objects"
repository = "https://github.com/bittoko/utils"
keywords = [ "utilities", "utils", "common", "nonce" ]
license = "MIT"

[dependencies]
test = "1.2.0"
xtended-numbers = "0.2.1"
base = "0.10.4"
map = "9.0.1"